services:
  db:
    image: postgres:16
    container_name: print_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # backend:
  #   build: ./backend
  #   container_name: print_backend
  #   restart: unless-stopped
  #   ports:
  #     - "5050:5050"
  #   environment:
  #     PORT: 5050
  #     NODE_ENV: development
  #     DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
  #     JWT_SECRET: ${JWT_SECRET}
  #     RESEND_API_KEY: ${RESEND_API_KEY}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   command: sh -c "pnpm run dev"

volumes:
  postgres_data:


#   frontend:
#     build: ./frontend
#     container_name: print_frontend
#     restart: unless-stopped
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     environment:
#       VITE_API_URL: http://backend:5000

# volumes:
#   postgres_data: