export const AUTH_ERRORS = {
  EMAIL_EXISTS: "Cet email est déjà utilisé",
  INVALID_CREDENTIALS: "Email ou mot de passe incorrect",
  INVALID_PASSWORD: "Mot de passe incorrect",
  ACCOUNT_DELETED:
    "Ce compte a été supprimé. Veuillez contacter le support pour le réactiver.",
  FAILED_CREATION: "Échec de la création de l'utilisateur",
  REQUIRED_FIRST_NAME: "Le prénom est requis",
  REQUIRED_LAST_NAME: "Le nom est requis",
  ROLE_IS_REQUIRED: "Le rôle est requis",
  NOT_ACTIVATE: "Ce compte n'est pas activé",
  INVITATION_NOT_FOUND: "Jeton d'invitation introuvable",
  INVITATION_USED: "Ce jeton d'invitation a déjà été utilisé",
  INVITATION_EXPIRED: "Ce jeton d'invitation a expiré",
  NOT_LOGGED_IN: "Veuillez vous connecter pour accéder à cette ressource",
  INVALID_TOKEN: "Jeton invalide ou expiré",
  NO_TOKEN_PROVIDED: "Aucun jeton fourni",
  FORBIDDEN: "Vous n'avez pas l'autorisation d'effectuer cette action",
  NO_PASSWORD_SET: "Aucun mot de passe n'a été défini pour ce compte",
  INVALID_CURRENT_PASSWORD: "Le mot de passe actuel est incorrect",
  TOKEN_ALREADY_USED: "Ce jeton a déjà été utilisé",
  TOKEN_EXPIRED: "Ce jeton a expiré",
  USER_NOT_FOUND: "Utilisateur introuvable",
} as const;
