export const AUTH_ERRORS = {
  EMAIL_EXISTS: "Email already exists",
  INVALID_CREDENTIALS: "Invalid email or password",
  INVALID_PASSWORD: "Invalid password",
  ACCOUNT_DELETED:
    "This account was deleted. Contact support to reactivate it.",
  USER_NOT_FOUND: "User not found",
  FAILED_CREATION: "Failed to create user",
  REQUIRED_FIRST_NAME: "First name is required",
  REQUIRED_LAST_NAME: "Last name is required",
  ROLE_IS_REQUIRED: "Role is required",
  NOT_ACTIVATE: "This accound is not activated",
  INVITATION_NOT_FOUND: "Invitation token not found",
  INVITATION_USED: "This invitation token has already been used",
  INVITATION_EXPIRED: "This invitation token has expired",
  NOT_LOGGED_IN: "Please login to access this resource",
  INVALID_TOKEN: "Invalid or expired token",
  NO_TOKEN_PROVIDED: "No token provided",
  FORBIDDEN: "You do not have permission to perform this action",
} as const;
