import { prisma } from "@/config/prisma.js";
import { Prisma } from "@/generated/prisma/client.js";
import { productSelect } from "./product.types.js"; // Ou importé localement
import type {
  CreateProductInput,
  UpdateProductInput,
  ProductQuery,
  PaginatedProductList,
} from "./product.types.js";

export class ProductRepository {
  // 1. Créer un produit complet avec ses variantes et ses règles de prix (Transaction imbriquée)
  async create(data: CreateProductInput, autogeneratedSlug: string) {
    return await prisma.product.create({
      data: {
        name: data.name,
        slug: autogeneratedSlug,
        variants: {
          create: data.variants.map((v) => ({
            name: v.name,
            pricingRules: {
              create: {
                pricingMode: v.pricingRule.pricingMode as any, // Cast nécessaire selon les enums Prisma
                config: v.pricingRule.config as Prisma.InputJsonValue,
              },
            },
          })),
        },
      },
      select: productSelect,
    });
  }

  // 2. Trouver un produit par son ID
  async findById(id: number) {
    return await prisma.product.findUnique({
      where: { id },
      select: productSelect,
    });
  }

  // 3. Trouver un produit par son Slug (Très utile pour le POS ou vérification)
  async findBySlug(slug: string) {
    return await prisma.product.findUnique({
      where: { slug },
      select: productSelect,
    });
  }

  // 4. Lister les produits avec pagination, recherche par mot-clé et tri
  async findAll(query: ProductQuery): Promise<PaginatedProductList> {
    const { page, limit, search, sortBy, sortOrder } = query;
    const skip = (page - 1) * limit;

    const where: Prisma.ProductWhereInput = {};

    // Recherche insensible à la casse sur le nom ou le slug du produit
    if (search) {
      where.OR = [
        { name: { contains: search, mode: "insensitive" } },
        { slug: { contains: search, mode: "insensitive" } },
      ];
    }

    const [products, total] = await Promise.all([
      prisma.product.findMany({
        where,
        select: productSelect,
        skip,
        take: limit,
        orderBy: { [sortBy]: sortOrder },
      }),
      prisma.product.count({ where }),
    ]);

    const totalPages = Math.ceil(total / limit);
    const hasMore = page < totalPages;

    return {
      data: products as any, // Mapping vers vos types de sortie FullProductOutput
      meta: {
        total,
        page,
        limit,
        totalPages,
        hasMore,
        search: search || undefined,
        sortBy,
        sortOrder,
      },
    };
  }

  // 5. Mettre à jour un produit et synchroniser ses variantes
  async update(id: number, data: UpdateProductInput, updatedSlug?: string) {
    // Note : La logique d'analyse de la mise à jour (savoir s'il faut recréer ou modifier les enfants)
    // est traitée dans le Service. Le repository exécute l'ordre Prisma de manière atomique.
    return await prisma.product.update({
      where: { id },
      data: {
        name: data.name,
        slug: updatedSlug,
        // La gestion des variantes complexes (Ajouts/Modifications/Suppressions)
        // se fera de manière sécurisée par des requêtes ciblées ou un connect/disconnect dans le Service.
      },
      select: productSelect,
    });
  }

  // 6. Supprimer un produit (Hard delete par défaut, car ON DELETE CASCADE nettoie les variantes et tarifs)
  async delete(id: number) {
    return await prisma.product.delete({
      where: { id },
    });
  }
}
