import { prisma } from "@/config/prisma.js";
import { Prisma } from "@/generated/prisma/client.js";
import { productSelect } from "./product.types.js";
import type {
  CreateProductInput,
  UpdateProductInput,
  ProductQuery,
  PaginatedProductList,
} from "./product.types.js";

export class ProductRepository {
  async create(data: CreateProductInput, autogeneratedSlug: string) {
    return await prisma.product.create({
      data: {
        name: data.name,
        slug: autogeneratedSlug,
        variants: {
          create: data.variants.map((v) => ({
            name: v.name,
            pricingRules: {
              create: {
                pricingMode: v.pricingRule.pricingMode as any,
                config: v.pricingRule.config as Prisma.InputJsonValue,
              },
            },
          })),
        },
      },
      select: productSelect,
    });
  }

  async findById(id: number) {
    return await prisma.product.findUnique({
      where: { id },
      select: productSelect,
    });
  }

  async findBySlug(slug: string) {
    return await prisma.product.findUnique({
      where: { slug },
      select: productSelect,
    });
  }

  async findAll(query: ProductQuery): Promise<PaginatedProductList> {
    const { page, limit, search, sortBy, sortOrder } = query;
    const skip = (page - 1) * limit;

    const where: Prisma.ProductWhereInput = {};

    if (search) {
      where.OR = [
        { name: { contains: search, mode: "insensitive" } },
        { slug: { contains: search, mode: "insensitive" } },
      ];
    }

    const [products, total] = await Promise.all([
      prisma.product.findMany({
        where,
        select: productSelect,
        skip,
        take: limit,
        orderBy: { [sortBy]: sortOrder },
      }),
      prisma.product.count({ where }),
    ]);

    const totalPages = Math.ceil(total / limit);
    const hasMore = page < totalPages;

    return {
      data: products as any,
      meta: {
        total,
        page,
        limit,
        totalPages,
        hasMore,
        search: search || undefined,
        sortBy,
        sortOrder,
      },
    };
  }

  async update(id: number, data: UpdateProductInput, updatedSlug?: string) {
    return await prisma.product.update({
      where: { id },
      data: {
        name: data.name,
        slug: updatedSlug,
      },
      select: productSelect,
    });
  }

  async delete(id: number) {
    return await prisma.product.delete({
      where: { id },
    });
  }
}
